main: com.kryeit.Stuff
version: 1.1
authors: [MuriPlz,MrRedRhino]
api-version: 1.18
softdepend: [AFKPlus,GriefDefender]
name: Stuff
commands:
  vr:
    description: Voting for my server rewards
  online:
    description: online players
    permission: stuff.online
  discord:
    description: sends discord link
  rules:
    description: sends rules link
  sendcoords:
    description: sends your cords to the player
    aliases:
      - sharecoords
  map:
    description: shows bluemap url
  vote:
    description: sends planetminecraft link
  kofi:
    description: sends kofi link
    aliases:
      - donate
  timeplayed:
    description: shows time played
  lastonline:
    description: shows last time online
  fly:
    description: makes you fly
    permission: stuff.fly
  invsee:
    description: gets a player inventory
    permission: stuff.invsee
  enderinvsee:
    description: gets a player enderchest
    permission: stuff.enderinvsee
  buylight:
    description: buys a light